### PR TITLE
Adding code to check for invalid licenses in license xml file

### PR DESCRIPTION
**Pull request by harshmadhani**
Added code to check if the licenses present in license xml file are valid, else it throw an exception

### CODE REVIEW

**Comment by harshmadhani** [comment]
@thescouser89 can you review the PR ?

**Comment by thescouser89** [comment]
@harshmadhani Could you please re-compile your code (so that code-format runs) and submit the rebased commit please? The checks fail because our code formatter is upset :(

Thanks!

**Comment by thescouser89** [comment]
@paulgallagher75 @michalszynkiewicz Could you please help reviewing this PR? I'm still not yet familiar with this area of code. Thanks! :)

**Comment by harshmadhani** [comment]
I have created a separate pull request with the proposed formatting changes. #213 is the new pull request. But it is failing with different errors other than the formatting issue that we were facing in this PR. @thescouser89 can you take a look at it?

**Comment by thescouser89** [comment]
It's ok now! :) I'll close this one if you don't mind, since it's a duplicate of #213

**Pull request closed without merging**
