### PR TITLE
[NCL-6200] Print pre-processed build-config.yaml

### PR DESCRIPTION
**Pull request by thescouser89**
### Checklist:

* [x] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [x] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
To be merged after #536

**Comment by rnc** [comment]
Can we get some unit tests for this please?

**Comment by thescouser89** [comment]
Ya I can add some. Give me a few days

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
I'll do a merge rather than a rebase and merge.

**Pull request merged**
