### PR TITLE
[NCLSUP-306] Disable CLI output with --no-color flag

### PR DESCRIPTION
**Pull request by thescouser89**
When running bacon in specific environment where the logs are piped into
files, the ANSI color commands show up in those logs and make them hard
to read.

This commit adds the --no-color flag to disable color/ANSI output in
picocli output. The user can also disable coloring by setting the
'NO_COLOR' environment variable with any value (https://no-color.org/).

We also remove the '%highlight' in the logback file to disable coloring
of the message level printed in stderr for logging.

ansi
ansi-log

### Checklist:

* [x] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by dwalluck** [comment]
I was fairly certain that picocli already supposed setting this env var, so it really wouldn't require any code changes.

**Comment by thescouser89** [comment]
Oh cool. I'll remove my check for NO_COLOR. I believe however the flag is required if the user wants to explicitly specify "I want no color" without having to set any env vars.

**Comment by dwalluck** [comment]
> Oh cool. I'll remove my check for NO_COLOR. I believe however the flag is required if the user wants to explicitly specify "I want no color" without having to set any env vars.

Yes, I figured maybe you wanted to do what it does with a flag instead of property or env var, but you didn't need additional logic to check for it. Sorry if I wasn't clear.

**Comment by thescouser89** [comment]
No worries! Thanks for pointing out about the `NO_COLOR` one. I didn't read far enough in the docs. Thank you! :)

**Review by dwalluck — APPROVED** [review]

**Pull request merged**
