### PR TITLE
Reverting jaxb version to 2.2.11 due to failures while running QuarkusCommunityDepAnalyzer add-on

### PR DESCRIPTION
**Pull request by harshmadhani**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
@harshmadhani do you know who did the problemmatic update? Maybe it's worth adding t his person as a reviewer, in case there was some specific reason to update.

**Comment by rnc** [comment]
It was that dependabot tool ( https://github.com/project-ncl/bacon/commit/e87ee7eac1c69858393e1cd1836578a7a944941b ) - I therefore think this change *must* have a test so any future change of this version is caught via a test failure.

**Comment by rnc** [comment]
@harshmadhani @michalovjan @thescouser89 I am also seeing 
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader
```
It seems that same PR is the cause. Is there a reason we need this dependabot running?

**Comment by michalszynkiewicz** [comment]
Let's merge it, @harshmadhani @RotBolt could you guys create a test for this add-on (if we don't have it already) in a separate PR?

**Comment by RotBolt** [comment]
Sure, we will create a test in next PR for this issue

**Pull request merged**
