### PR TITLE
change keyword to version-regexp

### PR DESCRIPTION
**Pull request by saumya1singh**
For #987  :)
cc @AntStephenson  @thescouser89

### CODE REVIEW

**Comment by AntStephenson** [comment]
Sorry about that, I tested locally, but I probably had a old license lying around 👍🏻 

@thescouser89 can you merge this please?

**Comment by saumya1singh** [comment]
no worries @AntStephenson  :) 
Thanks for adding the regex

**Comment by vardhmanJain** [comment]
> no worries @AntStephenson :) Thanks for adding the regex
> 
> @vardhmanJain when do you need this change in?

Today would be nice :)

**Comment by thescouser89** [comment]
Merged! Sorry for the slowness

**Comment by saumya1singh** [comment]
No issues, thank you @thescouser89

**Pull request merged**
