### PR TITLE
Add resolveArtifacts parameter of RESOLVE_ONLY

### PR DESCRIPTION
**Pull request by ppalaga**
This adds resolveArtifacts parameter of RESOLVE_ONLY Maven repo generation strategy. The usage is explained in this docs PR: https://github.com/project-ncl/bacon/pull/950

### CODE REVIEW

**Comment by ppalaga** [comment]
Any chance to review @thescouser89 ?

**Comment by ppalaga** [comment]
It would be nice to move this forward.

**Review by jomrazek — APPROVED** [review]
looks ok

**Comment by ppalaga** [comment]
Thanks for review and merge! When can we expect a release containing these changes?

**Comment by thescouser89** [comment]
@jomrazek ^^^^

**Comment by jomrazek** [comment]
@ppalaga oh hello, if you really need it and can't use snapshot we can release it, but we wanted to wait for Jonathan and security team to test their addon so we can release everything at once. Jonathan is on pto this week and they tasked some product teams with the testing few weeks ago so I'm planning to have it sorted and release new bacon next week

**Comment by ppalaga** [comment]
@jomrazek thanks for the update. It is not that hot on our side anymore as our product is being signed today. I'll be fully satisfied if you release in coming 1, 2 or 3 weeks.

**Pull request merged**
