### PR TITLE
retry downloads

### PR DESCRIPTION
**Pull request by michalszynkiewicz**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by rnc** [comment]
Can FileDownLoadUtils ever be called by multiple threads? i.e. could the `attempts` value be corrupted? Otherwise looks good to me.

**Comment by thescouser89** [comment]
Haa just a silly suggestion, but should we set the default attempts to a value greater than 1? Just to have some fault tolerance on by default.

Also tiny tiny tiny bug: if i set the attempts to be negative that could potentially create an infinite loop if the stuff we are downloading keeps failing.

**Comment by dwalluck** [comment]
> Haa just a silly suggestion, but should we set the default attempts to a value greater than 1? Just to have some fault tolerance on by default.

Why not?

> Also tiny tiny tiny bug: if i set the attempts to be negative that could potentially create an infinite loop if the stuff we are downloading keeps failing.

OK so `if retries <= 0: retries = 1 (or default_retries)`

**Comment by michalszynkiewicz** [comment]
> > Haa just a silly suggestion, but should we set the default attempts to a value greater than 1? Just to have some fault tolerance on by default.
> 
> Why not?

I'll set it to `2` for pig.

> 
> > Also tiny tiny tiny bug: if i set the attempts to be negative that could potentially create an infinite loop if the stuff we are downloading keeps failing.
> 
> OK so `if retries <= 0: retries = 1 (or default_retries)`

Good catch!

**Comment by thescouser89** [comment]
:+1:

**Pull request merged**
