### PR TITLE
Support for Maven repo generation that consists of multiple steps, e.g.

### PR DESCRIPTION
**Pull request by aloubyansky**
for generating Maven repos for multiple BOMs and then merging them into a single deliverable Maven repo ZIP

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [x] Have you added unit tests for your change?

### CODE REVIEW

**Comment by aloubyansky** [comment]
This change was added for use-cases originally discussed in https://issues.redhat.com/browse/QUARKUS-2221

**Comment by ppalaga** [comment]
It is rather unclear to me how is this supposed to work. @aloubyansky could you please document the new options in gh-pages branch and ideally also add some examples? Here is my old PR where I documented something in RESOLVE_ONLY https://github.com/project-ncl/bacon/pull/950/files

**Comment by aloubyansky** [comment]
Yes, I will a doc for sure. Unfortunately the testsuite is designed in a way that doesn't make it clear at all what config scenario is being tested.

**Comment by aloubyansky** [comment]
Here is a little doc https://github.com/project-ncl/bacon/pull/996

**Review by jomrazek — APPROVED** [review]
Generally looks good, I don't have some complicated configs for generation to test it but let's merge it and see.

**Comment by aloubyansky** [comment]
Thank you @jomrazek

**Pull request merged**
