### PR TITLE
[#338] Fix issues getting version

### PR DESCRIPTION
**Pull request by dwalluck**
* Close input stream
* Check for null pointers
* Don't create map to store instance
* Handle multiple jars on classpath

### CODE REVIEW

**Comment by rnc** [comment]
IMHO when this code already exists in dependent projects (e.g. PME) we should reuse that code and avoid duplication.

**Comment by dwalluck** [comment]
> Version #355

I guess you can only link to an issue and not another PR? Huh.

**Comment by thescouser89** [comment]
retest this please

**Comment by michalszynkiewicz** [comment]
@rnc says it's superseded by the merged #355 355

**Pull request closed without merging**
