### PR TITLE
NCL-6033: List operations on bacon are broken

### PR DESCRIPTION
**Pull request by dwalluck**
### Checklist:

* [x] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by dwalluck** [comment]
I think this is what was decided on. It's hard to add tests with no live test structure in place prior to this PR.

It;s also possible to do offline tests using wiremock. You have to set it up to capture some output of the commands first.

**Review by rnc — APPROVED** [review]
Looks good! I suspect there is no obvious way of testing this (without the work that @michalszynkiewicz  is putting in #444 )

**Comment by dwalluck** [comment]
I know how to get the wiremock captures, but it takes time. They have the advantage of being offline (except localhost), but they're harder to write.

If it requires a live server, then it's only going to be able to run in Jenkins or with additional config and access to internal servers, but they're easier to write as there is no mocking beforehand.

**Comment by rnc** [comment]
> I know how to get the wiremock captures, but it takes time. They have the advantage of being offline (except localhost), but they're harder to write.
> 

*Much* harder! If manual testing is ok, then I would vote to merge.

**Comment by dwalluck** [comment]
@thescouser89 didn't manually test last time which is how we didn't find out until later. He may want to try first this time.

**Review by thescouser89 — APPROVED** [review]
LGTM! Compiled locally and the list operations are working again!!! :)

**Pull request merged**
