### PR TITLE
Use lombok's UtilityClass on utility classes

### PR DESCRIPTION
**Pull request by dwalluck**
### For

* Class marked `static final` and all fields automatically marked `static`
* Private constructor created which throws `IllegalArgumentException`

### Against

* Can't be used in cases where we have an inner class that uses a public constructor, but maybe this isn't a great design to begin with
* Can't be used with `import static`. Once you use `@UtilityClass`, the compiler does not know that these fields are `static`.

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
I don't see much benefit in terms of code size, it makes what's going on less clear. Sorry, I'm a :-1: on it

**Comment by dwalluck** [comment]
> I don't see much benefit in terms of code size, it makes what's going on less clear. Sorry, I'm a 👎 on it

Then we likely shouldn't use it, but some classes should probably be updated manually. I will request some reviews to get some other opinions before closing, particular @rnc because he suggested it. Also, @michalszynkiewicz started neutral on it.

**Comment by michalszynkiewicz** [comment]
yes, I didn't know how `@Utility` works in practice then, sorry.

**Comment by rnc** [comment]
I am neutral on this, and I only mentioned it in passing on #381. I am not completely convinced its necessary apart from removing some IDE warnings? Given I changed a lot of the code when converting to picocli (hence the conflicts now) perhaps this should be dropped?

**Pull request closed without merging**
