### PR TITLE
Improve CLI arguments

### PR DESCRIPTION
**Pull request by janinko**

### CODE REVIEW

**Comment by thescouser89** [comment]
@janinko Thanks for the PR! I'm struggling to test for `--generic-parameter`:

```
➜  cli git:(janinko/arguments) ✗ java -jar cli/target/bacon.jar pnc build-config create --environment-id=100 --project-id=164 --build-script "mvn clean deploy"  --scm-repository-id 176 --scm-revision master --generic-parameter "test=true,no=false" --build-type MVN buildconfignameasdfasdf
[ERROR] - Missing argument/option: Option --generic-parameter, must be part of a property
➜  cli git:(janinko/arguments) ✗ java -jar cli/target/bacon.jar pnc build-config create --environment-id=100 --project-id=164 --build-script "mvn clean deploy"  --scm-repository-id 176 --scm-revision master --generic-parameter "test=true" --generic-parameter "no=false" --build-type MVN buildconfignameasdfasdf
[ERROR] - Missing argument/option: Option --generic-parameter, must be part of a property
```

I checked the documentation (https://aeshell.github.io/docs/option/index.html) but I'm still a bit unclear how to use it.

**Comment by janinko** [comment]
@thescouser89  Can you try it with = after the parameter? If that doesn't work I'll take a look, maybe it needs only single letter argument (like -D in java).
```
java -jar cli/target/bacon.jar pnc build-config create --environment-id=100 --project-id=164 --build-script "mvn clean deploy"  --scm-repository-id 176 --scm-revision master --generic-parameter="test=true" --generic-parameter="no=false" --build-type MVN buildconfignameasdfasdf
```

**Comment by thescouser89** [comment]
@janinko 

```
➜  cli git:(janinko/arguments) java -jar cli/target/bacon.jar pnc build-config create --environment-id=100 --project-id=164 --build-script "mvn clean deploy"  --scm-repository-id 176 --scm-revision master --generic-parameter="test=true" --generic-parameter="no=false" --build-type MVN buildconfignameasdfasdf
Enter your password: 
---
id: "258"
name: "buildconfignameasdfasdf"
description: null
buildScript: "mvn clean deploy"
scmRevision: "master"
creationTime: "2020-03-09T19:26:01.562Z"
modificationTime: "2020-03-09T19:26:01.563Z"
archived: false
buildType: "MVN"
scmRepository:
  id: "176"
  internalUrl: "git+ssh://code.stage.engineering.redhat.com/keycloak-nodejs-connect.git"
  externalUrl: null
  preBuildSyncEnabled: false
project:
  id: "164"
  name: "zz_3205283958472827114"
  description: null
  issueTrackerUrl: null
  projectUrl: null
environment:
  id: "100"
  name: "Demo Environment 1"
  description: "Basic Java and Maven Environment"
  systemImageRepositoryUrl: "my.registry/newcastle"
  systemImageId: "12345678"
  attributes:
    JDK: "1.7.0"
    OS: "Linux"
  systemImageType: "DOCKER_IMAGE"
  deprecated: false
dependencies: null
productVersion: null
groupConfigs: {}
parameters:
  ? ""
  : "no=false"

```

Looking at the buildconfig, it seems the key is now ':' with value "no=false"? It doesn't look quite right. It's missing the "test=true" also.

**Comment by janinko** [comment]
ok, I fugred it out. It mus follow just after the parameter, without space or equals:
```
$ java -jar cli/target/bacon.jar pnc build-config create foobar --environment-id 1 --project-id 1 --build-script "fail" --scm-repository-id 1 --scm-revision 1 --generic-parameterfoo=bar --generic-parameterbaz=bag
Map: {foo=bar, baz=bag}
key: foo value: bar
key: baz value: bag
```

**Comment by thescouser89** [comment]
@janinko  That doesn't look too good IMO. It looks less intuitive than the previous way.

**Comment by janinko** [comment]
> @janinko That doesn't look too good IMO. It looks less intuitive than the previous way.
yeah, I agree but the previous way couldn't handle values with commas IIRC. Another option would be to add short option `-P` (that reminded me, it should be --parameter, not --generic-parameter in new naming) so it will be:
```
$ java -jar cli/target/bacon.jar pnc build-config create foobar --environment-id 1 --project-id 1 --build-script "fail" --scm-repository-id 1 --scm-revision 1 -Pfoo=bar -Pbaz=bag
```
But I'm not sure what's the best here...

**Comment by thescouser89** [comment]
@janinko I don't mind the '-P<key>=<value>' option. Let's go with it for now!

**Comment by thescouser89** [comment]
@janinko Could you rebase your code so that we can merge it? :)

I also merged @dominikbrazdil 's PR renaming CUSTOM_PME_PARAMETERS to ALIGNMENT_PARAMETERS

**Comment by thescouser89** [comment]
retest this please

**Comment by janinko** [comment]
@thescouser89 @jomrazek There is problem with the -P option for --parameter ... it's already taken by  "PNC Configuration profile".

Suggestion for another letter? Or drop the short name for profile?

**Comment by jomrazek** [comment]
changing -p for config path to -cp or something and using -p for parameter?

**Comment by janinko** [comment]
Ready to merge?

**Comment by thescouser89** [comment]
Ah sorry for that merge conflict!!! I merged your other PR and that happened.

**Pull request merged**
