### PR TITLE
 Adding code to check for invalid licenses in license xml file

### PR DESCRIPTION
**Pull request by harshmadhani**
Adding code to check for invalid licenses in the license XML file. Also added description of the invalid licenses along with groupid and artifactid

### CODE REVIEW

**Comment by thescouser89** [comment]
The check failure is probably due to some changes in PNC 2.0 snapshot client changes. I'll have a look!

**Comment by thescouser89** [comment]
retest this please

**Comment by harshmadhani** [comment]
@thescouser89 thanks for the retriggering the check. @paulgallagher75 can you please help to review this PR?

**Comment by paulgallagher75** [comment]
The code looks fine for generated license xml checking

**Comment by michalszynkiewicz** [comment]
thanks @harshmadhani !

**Pull request merged**
