### PR TITLE
[NCL-5406] add websocket support to CLI

### PR DESCRIPTION
**Pull request by michalovjan**
Predisposition: https://github.com/project-ncl/pnc/pull/2895

### CODE REVIEW

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
Another predisposition: https://github.com/project-ncl/pnc/pull/2931

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
RETEST THIS PLEASE

**Comment by michalovjan** [comment]
retest this please

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
I fixed the CI by explicitly building PNC from master branch just before. That's I guess the safest thing to do to avoid inconsistencies.

**Pull request merged**
