### PR TITLE
Stop source artifact downloads from retrying

### PR DESCRIPTION
**Pull request by AntStephenson**
Only try once to download source artifacts as they can be missing (and from our repo there are a lot of missing source artifacts) which can cause the repo build time to be considerably larger. 

### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by rnc** [comment]
Shouldn't source artifacts always exist i.e. its rare they won't exist as the Gates mandate they exist? So shouldn't the repository be fixed instead?

**Comment by AntStephenson** [comment]
@rnc This is not the reality we see unfortunately - especially made worse when producing a BUILD_GROUP repository with all build deps too, there are quite a lot of third parties that do not have source jars available.

**Comment by rnc** [comment]
> @rnc This is not the reality we see unfortunately - especially made worse when producing a BUILD_GROUP repository with all build deps too, there are quite a lot of third parties that do not have source jars available.
> 
> Edit: Just to also point out by default source jars are optional and do not fail a Bacon Maven repository build probably for this reason exactly.

We should probably take this offline as its separate to this pr (no objections per se) but i thought the gates mandated source jars for every artifact i think?

**Comment by AntStephenson** [comment]
@rnc Happy to take it offline, can talk more about it on Monday.

**Review by thescouser89 — APPROVED** [review]
LGTM!

**Comment by thescouser89** [comment]
I'll merge this PR.

Thanks @AntStephenson for blessing us with your first contribution! Much appreciated :)

Please let me know also about the outcome of the discussion and we'll see!

**Pull request merged**
