### PR TITLE
[NCLSUP-244] release: only generate script+nvr list if data present

### PR DESCRIPTION
**Pull request by thescouser89**
### Checklist:

* [ ] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by rnc** [comment]
Sorry to be picky but when the CLI has: 
```
Commands:
  configure         Configure PNC entities
  build             Build
  run               Run all the steps
  repo              GenerateRepository
  licenses          GenerateLicenses
  javadocs          GenerateJavadocs
  sources           GenerateSources
  shared-content    GenerateSharedContentAnalysis
  docs              GenerateDocuments
  release           Push builds to brew, generate the NVR list, close the PNC milestone, generate the upload to candidates script
  pre-process-yaml  Show the final YAML content with variables injected
  addons            Addons
```
does 'run all the phases' include configure / preprocess / addons ? I am _guessing_ yes to the latter but no to the former two but I'm not sure :-)

**Comment by thescouser89** [comment]
That is a good question! Not pre-process-yaml, since I guess it's not really a step (but yeah how many users will know that!), but yes for configure and addons.

**Comment by rnc** [comment]
> That is a good question! Not pre-process-yaml, since I guess it's not really a step (but yeah how many users will know that!), but yes for configure and addons.

Ah so I was wrong :-) So maybe it needs to be "run all the steps i.e. all other commands listed except release & pre-process-yaml" ?

**Comment by thescouser89** [comment]
Yeah makes sense to me. I'll edit my pr to include pre-process-yaml also in the description. Thanks Nick for reviewing it and your suggestion! :)

**Review by rnc — APPROVED** [review]
Cool , I think that makes more sense. 
If we were being _really_ picky I think it should be `release & pre-process` to make the grammar flow better :-)

**Comment by thescouser89** [comment]
sure!

**Pull request merged**
