### PR TITLE
Add project logs

### PR DESCRIPTION
**Pull request by cunningt**
Adding project logs if 

printProjectLogs: true 

is set within the configuration.    Will add a PR to document it.

### CODE REVIEW

**Comment by cunningt** [comment]
PR for the documentation of this change

**Comment by rnc** [comment]
@cunningt I think the formatting for the PR is wrong ; I believe its possible to reformat but @thescouser89 or @jomrazek  would be able to clarify the command to run.

@thescouser89 In the build log, where it says `echo 'There are files with wrong formating. Exiting with FAIL` ; could that print the command the user's should run to correct their formatting?

**Comment by jomrazek** [comment]
just `mvn clean install`

**Comment by thescouser89** [comment]
Thanks @rnc for the suggestion! I have adjusted the Jenkins job to provide the instructions to fix it.

**Comment by thescouser89** [comment]
Thanks @cunningt for the PR and documentation PR! :heart:

**Pull request merged**
