### PR TITLE
Adding licenses for "com.github.java-json-tools jackson-coreutils" and "com.github.java-json-tools json-patch"

### PR DESCRIPTION
**Pull request by SaumyaSingh1**
CC @RotBolt, @harshmadhani

### CODE REVIEW

**Comment by thescouser89** [comment]
@SaumyaSingh1 Thanks for your first PR!  So exciting! :)

I think it's just a bit upset at the extra newlines you added at the end of the json file. Could you please remove them? Thank you!

**Comment by SaumyaSingh1** [comment]
> @SaumyaSingh1 Thanks for your first PR! So exciting! :)
> 
> I think it's just a bit upset at the extra newlines you added at the end of the json file. Could you please remove them? Thank you!

Aah sure thing, let me do that.
Thank you, Dustin :)

**Comment by thescouser89** [comment]
Weehee! Jenkins is happy, I am happy! Thanks for your first PR! :)

**Comment by SaumyaSingh1** [comment]
> Weehee! Jenkins is happy, I am happy! Thanks for your first PR! :)

Yayy, thank you 💙

**Pull request merged**
